### ISSUE TITLE
Invalid Turtle

### ISSUE THREAD

**Issue by namedgraph** [OpenLinkSoftware/lod-cloud#3]
Hi,

Have you validated the Turtle file? It's invalid.
On https://github.com/OpenLinkSoftware/lod-cloud/blob/master/LODCloud_SPARQL_Endpoints.ttl#L320 URI is missing the closing `>` - and many more.

**Comment by namedgraph** [comment]
I was about to fix this manually and make a PR, but there are to many errors for it to make sense.

Looks like the RDF was generated? What kind of tool are you using that does not write valid Turtle syntax?
If you don't fix the root cause and/or have a validator, it will continue to happen.

**Comment by kidehen** [comment]
This issue has been fixed, a while back. Posting here to close the matter. 
Proof includes some live tests.

[URIBurner About Service Page which includes an RDF-Turtle parser](http://linkeddata.uriburner.com/about/html/https://github.com/OpenLinkSoftware/lod-cloud/raw/master/LODCloud_SPARQL_Endpoints.ttl)

Since Virtuoso automagically includes prefixes, you can also test using the OSDS Browser extension which also works fine i.e., that would fail if prefixes aren't properly declared.
